services:
  - type: web
    name: private-office
    runtime: node
    plan: standard
    buildCommand: cd app && npm install --include=dev && npm run build
    startCommand: cd app && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://private_office_db_user:knAUXd4nIndbfxpi8VbAtyQm1GXVg5fE@dpg-d9h8ov37uimc738hb9rg-a.ohio-postgres.render.com/private_office_db
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        value: pk_test_cHJlY2lvdXMtZmluY2gtMC5jbGVyay5hY2NvdW50cy5kZXYk
      - key: CLERK_SECRET_KEY
        value: sk_test_JCEnIarjE62RAWn7TvgSeSPeUqHf9qZOiIrS2IHNX7
    healthCheckPath: /api/health
    disk:
      name: private-office-disk
      mountPath: /var/data
      sizeGB: 1
